### PR TITLE
Update runtime to 23.08

### PR DESCRIPTION
**Pull request by tim77**
Tested for some time, forks fine.

### CODE REVIEW

**Comment by bbhtt** [comment]
Hi, @tim77 can you bump it to 23.08? Thanks

**Comment by bbhtt** [comment]
Thanks, seems to be working from what I can tell. Merging.

**Comment by tim77** [comment]
Seems to works for me too. As for fix FEDC auto-checker i did only quick and dirty fix for now. Need to look more and improve probably because currently pattern looking only to `v30/30.8` branch.

**Comment by bbhtt** [comment]
Looks like they stopped updating the latest version here https://www.mersenne.org/download/?mirror=1 and they don't have something indicating the latest release. The pattern for the branch is separate from the version pattern on the tarball, x-checker can't resolve two isolated patterns.

If it doesn't work we'll probably need to manually update. I'm not sure what's the status of 30.16 is (pre-release/stable etc.) cc @dgcampea, @sat3ll

**Pull request merged**
